export default {
	number: /\d+/,
	paren: /[()]/,
	curly: /[{}]/,
	letter: /[a-z_]/i,
	bool: /(true|false)/i,
	whitespace: /\s/,
	quote: /\"/,
	comma: /,/,
	equals: /=/,
	plus: /\+/,
	minus: /\-/,
	multiply: /\*/,
	divide: /\//,
	exponent: /\^/,
	ampersand: /\&/,
	colon: /\:/,
	dot: /\./,
	exclamation: /\!/,
};
